plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: _sass/

title: "Rafael Zimmermann"
tagline: "An awesome tagline"
email: "softwareengineerl@chess.mozmail.com"
description: >- # this means to ignore newlines until "baseurl:"
author: Rafael Zimmermann
url: "https://rafaelzimmermann.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""
